### ISSUE TITLE
Does not work on IDEA 2018.2

### ISSUE THREAD

**Issue by hoegertn** [binxio/cfn-lint-plugin#1]
The plugin does not work on:

```
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

Downloading and installing from disk tells: Plugin is incompatible with this installation

**Comment by mvanholsteijn** [comment]
I just released version 0.1.1 which should work from build 181 onwards (And I actually tested it  on 2018.2)

**Comment by ghost** [comment]
Did not work on IntelliJ 2018.2 Windows 7 OS:

**Comment by mvanholsteijn** [comment]
@kalyankix I am investigating the issue..

**Comment by ghost** [comment]
Thanks @mvanholsteijn

**Comment by mvanholsteijn** [comment]
@kalyankix can you please try with version 0.1.3?

**Comment by hoegertn** [comment]
Is there a compiled version available?

**Comment by mvanholsteijn** [comment]
https://github.com/binxio/cfn-lint-plugin/files/2280501/cfn-lint-plugin-0.1.3.zip

**Comment by mvanholsteijn** [comment]
Could you please try https://github.com/binxio/cfn-lint-plugin/releases/download/0.1.2/cfn-lint-plugin-0.1.2.zip
