### ISSUE TITLE
Incompatible with IntelliJ 2020.1

### ISSUE THREAD

**Issue by catchin** [binxio/cfn-lint-plugin#11]
Thank you for providing this great integration plugin for IntelliJ. 

I just updated to the released 2020.1 version and the plugin is incompatible. Could you update the plugin to support the latest version?

**Comment by tracphil** [comment]
It was updated yesterday to support 2020.1.

**Comment by mvanholsteijn** [comment]
Indeed i did. I wish I could automate the process. It is pretty annoying...
