### ISSUE TITLE
plugin fails to install into PyCharm 2019 community edition

### ISSUE THREAD

**Issue by zaro0508** [binxio/cfn-lint-plugin#14]
cfn-lint plugin fails to install on PyCharm 2019 community edition.  I tried ver 0.1.3, 0.1.4, 0.1.5 and 0.1.6 all with the same result.. "Plugin cfn-lint is incompatible with this installation". https://pasteboard.co/JBSCj2V.png

PyCharm 2019.3.1 (Community Edition)
Build #PC-193.5662.61, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: AWSCloudFormation, aws.toolkit, com.intellij.plugin.adernov.powershell, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements

**Comment by mvanholsteijn** [comment]
I just released version 0.1.8a, which provides support for 2019.3.1. Hope this helps.
