### ISSUE TITLE
not working for yaml templates

### ISSUE THREAD

**Issue by jaymccon** [binxio/cfn-lint-plugin#2]
not getting any linting magic happening on yaml templates, works great for json though.

**Comment by mvanholsteijn** [comment]
@jaymccon I fixed the detection of appropriate files to lint in version 0.1.3. Can you please check it out?

https://github.com/binxio/cfn-lint-plugin/files/2280501/cfn-lint-plugin-0.1.3.zip

**Comment by jaymccon** [comment]
fixed, thanks @martijnvandongen 😄
