### ISSUE TITLE
Plugin doesn't seem to interface well with binary

### ISSUE THREAD

**Issue by leaumar** [binxio/cfn-lint-plugin#22]
I just installed/tried the intellij plugin (from the marketplace) for the first time. Figured out it needs an external install of `cfn-lint`, did `yarn global add cfn-lint`.

The following now happens every time I edit our `cf.yml`:
![image](https://user-images.githubusercontent.com/3950300/140101711-d4054282-be63-4b71-bab2-e5fb08f583f2.png)
![image](https://user-images.githubusercontent.com/3950300/140101717-e5ae43ad-e2ad-4b88-88f2-eabe9c712c2c.png)

System info:
![image](https://user-images.githubusercontent.com/3950300/140101756-7e397537-eed7-4fc4-ab39-7da30ba7b17e.png)
![image](https://user-images.githubusercontent.com/3950300/140101765-7dd3cd60-215e-469c-8137-7da31c803d21.png)
![image](https://user-images.githubusercontent.com/3950300/140101773-5dca121b-8a98-4a6d-b686-afe296b607cf.png)

Any help, please?

**Comment by mvanholsteijn** [comment]
Unfortunately, there are different products called 'cfn-lint'. We are supporting AWS's cfn-lint: https://github.com/aws-cloudformation/cfn-lint. Please following their installation instructions and point to it.

**Comment by leaumar** [comment]
Ok, I did `pip3 install cfn-lint`, resulting in this:
![image](https://user-images.githubusercontent.com/3950300/140104503-fe3b36ed-c1a2-48f2-a375-292d4cd23bbc.png)

But now when I edit cf.yml, I don't get validation warnings where I should (like an invalid resouce type), and a message I can't find the meaning of (I googled):
![image](https://user-images.githubusercontent.com/3950300/140104708-b6e666fc-a03a-4a74-ba5a-99d86d96cfb8.png)

What's this popup about?
