### ISSUE TITLE
Not compatible with IntelliJ IDEA 2022.3 version

### ISSUE THREAD

**Issue by volphy** [binxio/cfn-lint-plugin#27]
`Plugin 'cfn-lint' (version '0.1.24') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is IU-223.7571.182`

**Comment by andreasfranz** [comment]
I've create a PR for this https://github.com/binxio/cfn-lint-plugin/pull/28

**Comment by mvanholsteijn** [comment]
@andreasfranz  thank you, thank you, thank you! The PR has been merged and version 0.1.25 has been published.
