### ISSUE TITLE
Does not work on Pycharm 2018.3

### ISSUE THREAD

**Issue by zaro0508** [binxio/cfn-lint-plugin#3]
cfn-lint ver 0.1.3 does not work with Pycharm 2018.3 community edition.  Install plugin from disk then it says.. "Plugin cfn-lint is incompatible with this installation". https://imgur.com/a/CazKyir

PyCharm 2018.3 (Community Edition)
Build #PC-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by zaro0508** [comment]
I was able to install [ver 0.1.1](https://github.com/binxio/cfn-lint-plugin/releases/download/0.1.1/cfn-lint-plugin-0.1.1.zip) without error though.

**Comment by mvanholsteijn** [comment]
thanks for reporting. I updated the plugin to version 0.1.4 to support 2018.3. 

Version 0.1.4 of the cfn-lint plugin has been approved by JetBrains and is now publicly available by the following link: https://plugins.jetbrains.com/plugin/10973-cfn-lint/update/52796.
