### ISSUE TITLE
Please update for Pycharm 2019.1

### ISSUE THREAD

**Issue by zfil** [binxio/cfn-lint-plugin#5]

**Comment by gene1wood** [comment]
@mvanholsteijn currently this plugin doesn't work in jetbrains IDEs showing this error in PyCharm 2019.1 for example

![cfn-lint-not-working-in-pycharm-2019 1](https://user-images.githubusercontent.com/1134034/57338223-6ff83200-70e1-11e9-8788-7aa8b2cf489c.png)

**Comment by mvanholsteijn** [comment]
Hi @gene1wood , I just released version 0.1.5 which does support 2019.1. It did have a code incompatibility with 2018.3. Cheers, Mark

**Comment by gene1wood** [comment]
Confirmed, this fix resolved the problem.
