### ISSUE TITLE
Incompatible with Intellij 2019.2

### ISSUE THREAD

**Issue by otbe** [binxio/cfn-lint-plugin#7]
Hi,

first of all thank you for this amazing plugin. 👍
I would like to let you know thats incompatible with the most recent version of Intellij (and maybe other IDEs).

I dont have any experience with Intellij plugins but If I can help you let me know.

Thanks ☺️

**Comment by mvanholsteijn** [comment]
working on it. The build crashes with 2019.2.

**Comment by mvanholsteijn** [comment]
upgrading currently stuck on https://youtrack.jetbrains.com/issue/KT-32401

**Comment by ivan-moto** [comment]
Any update on this?

**Comment by zfil** [comment]
Hello @mvanholsteijn I'm using the plugin successfully on 2019.2.x ... the only thing I've changed is update the gradle build:
intellij {
    version '2019.2'
}
